<!DOCTYPE html>
<html>
<body>

<center><img class="img-fluid" src="assets/images/ginjal.jpg"></center>

<br>

<div class="title-tag-container" style="box-sizing: border-box; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0px 17px; color: rgb(0, 0, 0); font-family: LatoWeb, sans-serif; text-align: start;">
    <h1 style="box-sizing: border-box; margin: 10px 0px; font-weight: bold; line-height: 1.2; font-size: 24px; color: rgb(0, 0, 0); text-align: justify;">Penyakit Ginjal</h1>
</div>

<div class="text-justify" style='box-sizing: border-box; text-align: justify !important; color: rgb(79, 79, 79); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
    <div class="post-detail-container" style="box-sizing: border-box; margin-bottom: 25px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <div class="post-content" style="box-sizing: border-box; line-height: 1.75;">
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; text-align: justify;">Penyakit ginjal adalah istilah yang menggambarkan setiap gangguan yang terjadi pada ginjal. Penyakit ginjal akan mengganggu fungsi organ ini untuk membersihkan dan menyaring limbah atau racun dari darah.</p>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; text-align: justify;">Ginjal adalah sepasang organ berbentuk seperti kacang yang berada di area punggung bagian bawah. Saat ginjal mengalami gangguan, beragam komplikasi mulai dari penumpukan limbah dan racun, anemia, serta gangguan elektrolit, bisa terjadi. Oleh karena itu, penting untuk menjaga kesehatan ginjal dan melakukan pencegahan penyakit ginjal sejak dini.</p>
            <h3 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Jenis-jenis Penyakit Ginjal</h3>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Sebelum mengenal beragam faktor penyebab penyakit ginjal, ada beberapa jenis penyakit ginjal yang umum terjadi, yaitu:</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Penyakit ginjal kronis atau gagal ginjal kronis</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Kerusakan ginjal pada kondisi ini menyebabkan penurunan fungsi ginjal secara bertahap selama lebih dari 3 bulan.&nbsp;Gagal ginjal kronis sering disebabkan oleh diabetes tipe 1 dan 2, hipertensi, penyakit autoimun, atau penyakit infeksi pada ginjal.</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Gagal ginjal akut</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pada penyakit ginjal ini, terjadi penurunan fungsi ginjal secara tiba-tiba.&nbsp;Gagal ginjal akut sering disebabkan oleh kekurangan cairan dan darah, cedera pada ginjal, atau sumbatan yang menyebabkan kembalinya cairan ke ginjal.</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Batu ginjal</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Penyakit&nbsp;batu ginjal ini disebabkan oleh penumpukan zat dan mineral yang kemudian membentuk batu di ginjal. Kondisi ini sering dipicu oleh penyakit asam urat atau infeksi saluran kemih.</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Penyakit ginjal polikistik</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Penyakit ginjal polikistik menyebabkan terbentuknya kista-kista (kantong-kantong berisi cairan) di ginjal, dan penyebabnya adalah kelainan genetik.</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Infeksi ginjal</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Infeksi ginjal bisa disebabkan oleh bakteri, virus, atau jamur. Penyakit ginjal ini juga dapat terjadi akibat penyebaran infeksi pada saluran kemih ke ginjal.</p>
            <h3 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Penyebab Penyakit Ginjal</h3>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Ada&nbsp;beberapa faktor yang secara umum bisa meningkatkan risiko terjadinya penyakit ginjal, yaitu:</p>
            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; text-align: justify;">Menderita diabetes, hipertensi, penyakit jantung, atau penyakit hati</li>
                <li style="box-sizing: border-box; text-align: justify;">Memiliki keluarga yang juga menderita penyakit ginjal</li>
                <li style="box-sizing: border-box; text-align: justify;">Mengalami&nbsp;infeksi saluran kemih atau infeksi ginjal yang berulang</li>
                <li style="box-sizing: border-box; text-align: justify;">Menderita&nbsp;obesitas</li>
                <li style="box-sizing: border-box; text-align: justify;">Memiliki pola makan yang tinggi kandungan garam atau gula</li>
                <li style="box-sizing: border-box; text-align: justify;">Memiliki kebiasaan jarang minum air putih sehinga meningkatkan risiko kekurangan cairan</li>
                <li style="box-sizing: border-box; text-align: justify;">Berusia lanjut</li>
                <li style="box-sizing: border-box; text-align: justify;">Memiliki sistem imun yang lemah atau menderita penyakit autoimun</li>
                <li style="box-sizing: border-box; text-align: justify;">Memiliki kelainan bentuk ginjal</li>
            </ul>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Selain itu, paparan zat kimia tertentu secara berlebihan, seperti&nbsp;melamin, juga dapat meningkatkan risiko terjadinya penyakit ginjal.</p>
            <h3 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Gejala Penyakit Ginjal</h3>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Ginjal merupakan sepasang organ dengan bentuk menyerupai kacang merah yang terletak di area punggung bawah, tepatnya di bawah tulang rusuk. Ginjal merupakan organ yang sangat penting dan memiliki beragam fungsi.</p>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Beberapa&nbsp;fungsi ginjal adalah untuk menyaring limbah dan racun dari darah, menjaga keseimbangan cairan, elektrolit, dan asam basa di dalam tubuh, menstimulasi pembentukan sel darah merah, mengatur tekanan darah, serta membantu pengaktifan vitamin D.</p>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Penyakit ginjal akan mengganggu fungsi-fungsi tersebut. Secara umum, ada beberapa gejala yang bisa mengindikasikan gangguan pada ginjal, yaitu:</p>
            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; text-align: justify;">Penurunan volume urine</li>
                <li style="box-sizing: border-box; text-align: justify;">Perubahan warna pada urine, termasuk urine keruh atau&nbsp;bercampur darah</li>
                <li style="box-sizing: border-box; text-align: justify;">Pembengkakan pada tungkai</li>
                <li style="box-sizing: border-box; text-align: justify;">Muncul nyeri pada punggung bagian bawah, nyeri nya dapat menjalar ke perut bawah atau selangkangan</li>
                <li style="box-sizing: border-box; text-align: justify;">Muncul nyeri saat buang air kecil</li>
                <li style="box-sizing: border-box; text-align: justify;">Muncul kram kram otot dan kedutan</li>
                <li style="box-sizing: border-box; text-align: justify;">Mual, muntah, dan&nbsp;kehilangan nafsu makan</li>
                <li style="box-sizing: border-box; text-align: justify;">Sering merasa kelelahan dan&nbsp;sesak napas</li>
                <li style="box-sizing: border-box; text-align: justify;">Kulit terasa gatal yang tidak diketahui penyebab pastinya</li>
                <li style="box-sizing: border-box; text-align: justify;">Peningkatan tekanan darah</li>
                <li style="box-sizing: border-box; text-align: justify;">Anemia</li>
            </ul>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Gejala-gejala di atas bisa muncul secara tiba-tiba atau secara bertahap, sesuai dengan jenis penyakit ginjal yang diderita.</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Kapan harus ke dokter</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Lakukan pemeriksaan&nbsp;ke dokter jika Anda mengalami keluhan dan gejala yang disebutkan di atas. Pemeriksaan sejak dini diperlukan untuk mengetahui penyebab keluhan yang dirasakan. Penanganan sejak dini juga bisa mencegah komplikasi akibat penyakit ginjal.</p>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Jika Anda memiliki kondisi yang bisa meningkatkan risiko terjadinya gangguan ginjal, lakukan pemeriksaan secara rutin kedokter untuk mengontrol kondisi Anda dan mencegah terjadinya penyakit ginjal.</p>
            <h3 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Diagnosis Penyakit Ginjal</h3>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Dokter akan menanyakan gejala yang dialami pasien serta riwayat kesehatan pasien dan keluarganya. Setelah itu, dokter akan melakukan pemeriksaan fisik dengan menekan area pinggang pasien untuk mendeteksi rasa nyeri, melihat tanda-tanda pembengkakan di tungkai, atau mengindentifikasi tanda infeksi, seperti demam.</p>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Selanjutnya, dokter akan melakukan beberapa pemeriksaan penunjang yang meliputi:</p>
            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; text-align: justify;">Tes darah, untuk mengetahui&nbsp;fungsi ginjal melalui pemeriksaan kadar ureum kreatinin, melihat kadar elektrolit, dan jumlah sel-sel darah</li>
                <li style="box-sizing: border-box; text-align: justify;">USG ginjal, untuk melihat struktur dan kondisi ginjal, serta mendeteksi adanya pembengkakan, kista, atau tumor</li>
                <li style="box-sizing: border-box; text-align: justify;">Tes urine, untuk mengetahui ada tidaknya albumin atau protein, bakteri, dan darah di dalam urine</li>
                <li style="box-sizing: border-box; text-align: justify;">Biopsi ginjal, untuk mengetahui ada tidaknya kerusakan atau perubahan sel dan jaringan ginjal</li>
            </ul>
            <h3 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pengobatan Penyakit Ginjal</h3>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pengobatan penyakit ginjal bertujuan untuk meringankan gejala, mengatasi penyebab, memperlambat perkembangan penyakit, dan mencegah komplikasi. Pengobatan penyakit ginjal akan disesuaikan dengan penyebab dan kondisi keparahan penyakitnya.</p>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Secara umum, ada beberapa pilihan pengobatan yang dapat dilakukan, yaitu:</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pemberian obat-obatan</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Obat-obatan akan diberikan oleh dokter sesuai dengan penyebab dari penyakit ginjal. Beberapa pilihan obat yang mungkin akan diberikan oleh dokter adalah:</p>
            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; text-align: justify;">Obat pengontrol darah tinggi, seperti&nbsp;ACE inhibitor dan&nbsp;angiostensin II receptor blockers (ARB), untuk menurunkan tekanan darah, menjaga fungsi ginjal, dan memperlambat kerusakan ginjal.</li>
                <li style="box-sizing: border-box; text-align: justify;">Obat untuk mengontrol kadar kalium di dalam darah, guna mencegah komplikasi seperti jantung berdebar dan otot lemas.</li>
                <li style="box-sizing: border-box; text-align: justify;">Antibiotik, untuk mengatasi infeksi bakteri pada ginjal. Obat dapat diberikan secara oral atau suntikan tergantung tingkat keparahan infeksi.</li>
                <li style="box-sizing: border-box; text-align: justify;">Obat diuretik, untuk menyeimbangkan cairan tubuh. Obat ini juga diberikan untuk mengurangi pembengkakan di tungkai.</li>
                <li style="box-sizing: border-box; text-align: justify;">Obat pereda nyeri, seperti&nbsp;paracetamol dan ibuprofen, untuk meringankan nyeri hebat yang terjadi pada area punggung dan perut.</li>
                <li style="box-sizing: border-box; text-align: justify;">Obat untuk melemaskan otot saluran kemih, seperti&nbsp;alpha blocker. Obat ini diberikan pada penyakit ginjal yang disebabkan oleh&nbsp;batu ginjal. Tujuannya adalah agar batu dapat lebih mudah dikeluarkan.</li>
            </ul>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Perubahan gaya hidup</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Sambil mengonsumsi obat-obatan, pasien juga diminta melakukan perubahan gaya hidup guna meringankan kerja ginjal. Hal yang perlu dilakukan adalah:</p>
            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; text-align: justify;">Mengurangi asupan garam, gula, dan makanan tinggi kolesterol</li>
                <li style="box-sizing: border-box; text-align: justify;">Melakukan kontrol&nbsp;diabetes, hipertensi, penyakit autoimun, secara teratur</li>
                <li style="box-sizing: border-box; text-align: justify;">Mengonsumsi air putih minimal 2&ndash;3 liter per hari</li>
                <li style="box-sizing: border-box; text-align: justify;">Membatasi konsumsi alkohol dan berhenti merokok</li>
                <li style="box-sizing: border-box; text-align: justify;">Memperbanyak konsumsi buah, sayur, dan biji-bijian utuh</li>
                <li style="box-sizing: border-box; text-align: justify;">Rutin berolahraga agar berat badan tetap stabil</li>
            </ul>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Penghancuran batu ginjal</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Jika pasien memiliki batu ginjal dengan ukuran yang cukup besar, batu tersebut akan dihancurkan dengan teknik&nbsp;extracorporeal shock wave lithotripsy atau dengan teknik&nbsp;ureteroscopic lithotripsy.</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Cuci darah</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Jika ginjal pasien sudah tidak bisa lagi berfungsi dengan baik, dokter akan menyarankan dialisis (cuci darah). Dialisis adalah prosedur medis untuk menggantikan fungsi ginjal dalam menyaring darah dan membuang limbah serta racun dari dalam tubuh. Cuci darah bisa berlangsung selama 3&ndash;5 jam dan bisa dilakukan sekitar 3 kali per minggu.</p>
            <h4 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Operasi</h4>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Operasi umumnya dipilih bila cara penanganan lain tidak efektif. Berikut adalah sejumlah operasi yang dapat dilakukan dalam menangani penyakit ginjal:</p>
            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; text-align: justify;">Operasi pengangkatan kista dari ginjal, bila penderita penyakit ginjal polikistik memiliki kista berukuran besar dan menyebabkan nyeri hebat.</li>
                <li style="box-sizing: border-box; text-align: justify;">Operasi pengangkatan batu ginjal, bila penderita memiliki batu ginjal dengan ukuran yang cukup besar.</li>
                <li style="box-sizing: border-box; text-align: justify;">Transplantasi ginjal, yaitu operasi penggantian ginjal pasien dengan ginjal sehat dan cocok dari&nbsp;donor.</li>
            </ul>
            <h3 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Komplikasi Penyakit Ginjal</h3>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Jika tidak segera ditangani, penyakit ginjal dapat menyebabkan komplikasi, seperti:</p>
            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; text-align: justify;">Hipertensi</li>
                <li style="box-sizing: border-box; text-align: justify;">Edema paru</li>
                <li style="box-sizing: border-box; text-align: justify;">Hiperkalemia</li>
                <li style="box-sizing: border-box; text-align: justify;">Penyakit jantung</li>
                <li style="box-sizing: border-box; text-align: justify;">Kerusakan saraf</li>
                <li style="box-sizing: border-box; text-align: justify;">Sepsis</li>
                <li style="box-sizing: border-box; text-align: justify;">Kerusakan ginjal permanen</li>
            </ul>
            <h3 style="box-sizing: border-box; margin-top: 32px; margin-bottom: 0px; font-weight: bold; line-height: 1.32; font-size: 17px; color: rgb(59, 55, 56); font-style: normal; font-stretch: normal; letter-spacing: -0.3px; font-family: LatoWeb, sans-serif; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pencegahan Penyakit Ginjal</h3>
            <p style="box-sizing: border-box; margin: 10px 0px; font-size: 16px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Cara terbaik untuk mencegah penyakit ginjal adalah dengan menjaga kesehatan ginjal. Ada beberapa hal yang dapat dilakukan, yaitu:</p>
            <ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: border-box; text-align: justify;">Memperbanyak&nbsp;konsumsi air putih, yaitu sekitar 2 liter per hari</li>
                <li style="box-sizing: border-box; text-align: justify;">Menerapkan&nbsp;pola makan yang sehat dan bergizi seimbang</li>
                <li style="box-sizing: border-box; text-align: justify;">Melakukan kontrol kesehatan berkala, terlebih jika memiliki penyakit diabetes, hipertensi, atau penyakit autoimun</li>
                <li style="box-sizing: border-box; text-align: justify;">Menghentikan kebiasaan merokok</li>
                <li style="box-sizing: border-box; text-align: justify;">Membatasi konsumsi alkohol</li>
                <li style="box-sizing: border-box; text-align: justify;">Menjaga berat badan ideal, salah satunya dengan rutin berolahraga</li>
            </ul>
        </div>
    </div>
</div>

</body>
</html>