<!DOCTYPE html>
<html>
<body>

<div class="title-tag-container" style="margin: 0px 0px 17px; color: rgb(0, 0, 0); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h1 style="margin: 10px 0px; font-size: 24px; font-weight: bold; color: rgb(0, 0, 0);"><br></h1>
    <h1 style="margin: 10px 0px; font-size: 24px; font-weight: bold; color: rgb(0, 0, 0);">Cek Gejala Penyakit Ginjal</h1>
</div>
<div class="post-detail-container" style="margin-bottom: 25px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="post-content" style="line-height: 1.75;">
    <form method="post">
        <p style="font-size: 16px; margin: 10px 0px;">Silahkan anda ceklis sesuai dengan gejala yang dirasakan dibawah ini</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nyeribak">  Nyeri saat buang air kecil</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="seringbak">  Sering buang air kecil</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="demamgil">  Demam dan Mengigil</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nyeriping">  Nyeri pinggang</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nyeriper">  Nyeri perut</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="urinkeruhbau">  Urine keruh dan berbau busuk</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="urindarah">  Urine berdarah</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="mual">  Mual dan muntah</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nyeripung">  Nyeri punggung</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="bakpanas">  Buang air kecil terasa panas</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="bakdikit">  Buang air kecil sedikit atau anyang-anyangan</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="bakkurang">  Jumlah atau frekuensi urine berkurang</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kakkai">  Pembengkakan pada tungkai</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="lelah">  Tubuh mudah lelah</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="sesak">  Sesak Napas</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="iramajan">  Gangguan irama jantung</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nyeridada">  Nyeri atau esensi tertekan di dada</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="napasbau">  Napas berbau tak sedap</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="ruam">  Muncul ruam atau rasa gatal dikulit</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nafsumakan">  Nafsu makan menurun</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kaksendi">  Nyeri atau pembekakan pada sendi</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="tremor">  Tremor ditangan</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kejang">  Kejang</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="koma">  Koma</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nafsumakanx">  Kehilangan nafsu makan</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="gatal">  Kulit gatal berkepanjangan</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="bb">  Penurunan berat badan atau malah meningkat</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="malam">  Saat malam hari, lebih sering buang air</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kakmatakaki">  Pembengkakan pada mata kaki atau tangan</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="darahtinggi">  Tekanan darah tinggi yang sulit dikendalikan</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="tidur">  Gangguan tidur</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kram">  Kram dan kejang otot</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="pucat">  Pucat</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="pusing">  Pusing</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="ereksi">  Disfungsi ereksi (Pria)</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="imbang">  Gangguan keseimbangan</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nelan">  Kesulitan menelan</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="keringat">  Keringat berlebih atau berkurang</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="vagina">  Vagina kering</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="libido">  Penurunan libido</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="diare">  Sembelit atau diare atau bergantian</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kemih">  Gangguan berkemih, seperti mengompol atau sulit buang air kecil</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="buram">  Penglihatan buram atau ganda</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="lumpuh">  Lumpuh pada salah satu sisi wajah</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="berdebar">  Jantung berdebar</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="edema">  Edema</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="busa">  Urine berbusa</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="naikbb">  Berat badan bertambah</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="letih">  Letih dan lesu</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nyerigul">  Nyeri panggul</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="nanah">  Nanah pada urine</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kakwajah">  Pembekakan pada wajah dan kaki</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kakpung">  Benjolan atau bengkak disekitar punggung bawah dan pinggang</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="keringatmalam">  Keringat banyak pada malam hari</p>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><input type="checkbox" name="kurangdarah">  Kekurangan darah</p>
        <button type="submit" name="enter" class="btn btn-primary">Kirim</button>
    </form>
    </div>
</div>
<?php
    if(isset($_POST['enter'])){
        ?>
        <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Berikut hasil yang kami dapatkan : </p>
        <?php
        if(isset($_POST['nyeribak']) and isset($_POST['seringbak']) and isset($_POST['demamgil']) and isset($_POST['nyeriping']) and isset($_POST['nyeriper']) and isset($_POST['urinkeruhbau']) and isset($_POST['urindarah']) and isset($_POST['mual'])){
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Infeksi Ginjal.</p>
            <?php
        }
        elseif(isset($_POST['nyeriping']) and isset($_POST['nyeripung']) and isset($_POST['neriper']) and isset($_POST['bakpanas']) and isset($_POST['seringbak']) and isset($_POST['urinkeruhbau']) and isset($_POST['bakdikit']) and isset($_POST['mual']) and isset($_POST['demamgil'])){
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Batu Ginjal.</p>
            <?php
        }
        elseif(isset($_POST['bakkurang']) and isset($_POST['kakkai']) and isset($_POST['lelah']) and isset($_POST['sesak']) and isset($_POST['iramajan']) and isset($_POST['nyeridada']) and isset($_POST['napasbau']) and isset($_POST['ruam']) and isset($_POST['nafsumakan']) and isset($_POST['mual']) and isset($_POST['demamgil']) and isset($_POST['nyeriper']) and isset($_POST['nyeripung']) and isset($_POST['kaksendi']) and isset($_POST['tremor']) and isset($_POST['kejang']) and isset($_POST['koma'])){
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Gagal Ginjal Akut.</p>
            <?php
        }
        elseif(isset($_POST['mual']) and isset($_POST['nafsumakanx']) and isset($_POST['gatal']) and isset($_POST['bb']) and isset($_POST['malam']) and isset($_POST['urindarah']) and isset($_POST['edema']) or isset($_POST['kakkai']) or isset($_POST['kakmatakaki']) and isset($_POST['nyeridada']) and isset($_POST['sesak']) and isset($_POST['darahtinggi']) and isset($_POST['tidur']) and isset($_POST['kram']) and isset($_POST['pucat']) and isset($_POST['pusing']) and isset($_POST['ereksi'])){
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Gagal Ginjal Kronis.</p>
            <?php
        }
        elseif(isset($_POST['imbang']) and isset($_POST['nelan']) and isset($_POST['keringat']) and isset($_POST['ereksi']) and isset($_POST['vagina']) and isset($_POST['libido']) and isset($_POST['diare']) and isset($_POST['kemih']) and isset($_POST['buram']) and isset($_POST['lumpuh']) and isset($_POST['berdebar'])){
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Neuropati Diabetik.</p>
            <?php
        }
        elseif(isset($_POST['edema']) and isset($_POST['busa']) and isset($_POST['diare']) and isset($_POST['letih']) and isset($_POST['nafsumakanx']) and isset($_POST['naikbb'])){
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Sindrom Nefrotik.</p>
            <?php
        }
        elseif(isset($_POST['seringbak']) and isset($_POST['bakpanas']) and isset($_POST['nyeripang']) and isset($_POST['urinkeruhbau']) and isset($_POST['urindarah']) and isset($_POST['nanah']) and isset($_POST['nyeriping']) or isset($_POST['nyeriper']) and isset($_POST['mual']) and isset($_POST['demam']) and isset($_POST['darahtinggi']) and isset($_POST['kakwajah'])){
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Sindrom Nefritik.</p>
            <?php
        }
        elseif(isset($_POST['kakpung']) and isset($_POST['nyeripung']) and isset($_POST['nyeriping']) and isset($_POST['demamgil']) and isset($_POST['keringatmalam']) and isset($_POST['bb']) and isset($_POST['nafsumakanx']) and isset($_POST['pucat']) and isset($_POST['lelah']) and isset($_POST['urindarah']) and isset($_POST['kurangdarah'])){
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Gagal Ginjal Kronis.</p>
            <?php
        }
        else{
            ?>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Maaf, kami tidak dapat mengidentifikasi gejala yang anda derita.</p>
            <p style="font-size: 16px; margin: 10px 0px; color: rgb(59, 55, 56); font-family: LatoWeb, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Silahkan anda periksa langsung ke dokter. Karna kami tidak dapat mengidentifikasi penyakit anda.</p>
            <?php
        }
    }
?>
</body>
</html>